### ISSUE TITLE
troubleshooting episodes

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/2020-01-17-UCSB-git#2]
Jon and Torin are documenting which eposides cause the site not to build.  Currently it's building with: 5, 6, 8, 10, 11, 12, 13, 14.

The most recent delete was 3.  I'm pretty sure 4 and 9 also break it.

**Comment by jonjab** [comment]
Episodes 1, 3, 4, 7 for sure breaks it.

9 still needs to be tested.

**Comment by jonjab** [comment]
Confirmed:  Episodes 1,3,4,7, and 9 break the site build.

**Comment by torwhite** [comment]
Fixed with additional of missing files that caused site to break
