### ISSUE TITLE
Bundler::GemNotFound

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/2020-01-17-UCSB-git#3]
This repo seems to suffer from the same issue as we had on the Bash workshop

https://github.com/UCSBCarpentry/2020-01-17-UCSB-bash/issues/1

This is the error I get when I try to build the site locally:

```
~/.gem/ruby/2.3.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:287:
  in `block in verify_gemfile_dependencies_are_found!': 
  Could not find gem 'github-pages' in any of the gem sources listed in your Gemfile.
  (Bundler::GemNotFound)
```

**Comment by torwhite** [comment]
Jon deleted file causing issue previously
